<div class="container-fuild" style="float:left;width:100%;background-color:#e6e6e6;padding:10px 4% 12px 4%;">
	<?php print_r($slider); ?>
</div>
<section class="content-section" style="background-color:#fff;padding:20px 0;float:left;width:100%;">
	<div class="container-fuild" style="padding-left:4%;padding-right:4%;">
		<div class="row">
<div class="col-sm-3 video-sec wow fadeInLeft" data-wow-delay="0.5s" style="width:21%;" >
			<div class="sidebar-header-title"><span class="e-text"><?php echo $this->lang_file->heading_fetch('eNAM');?> <?php echo $this->lang_file->heading_fetch('elearningvideos');?></span></div>
			<div class="row">
			<?php if(isset($videos) && count($videos)>0){?>
				<?php $c = 1; foreach($videos as $video){ ?>
				<div class="col-md-12">
					<div class="row elearn-v-box">
						<div class="col-md-12" style="padding-right:0px;">
<div style="border:1px solid #d6d3d3;float:left;padding:3px;"><?php $v = explode('/embed/',$video['v_url']); ?>
						<div class="rahul_youtube" id="iframe1_v_<?php echo $c;?>" data-id="<?php echo $c;?>" data-v_id="iframe1_v_<?php echo $c;?>" data-v_url="<?php echo $video['v_url']; ?>" style="background:url('http://img.youtube.com/vi/<?php echo $v[1];?>/0.jpg') center no-repeat;cursor:pointer;height:125px;width:229px;background-size:cover;"></div>
<h3><?php echo $video['v_title']; ?></h3>
<img style="width:64px;"  data-v_id="iframe_v_<?php echo $c;?>" data-v_url="<?php echo $video['v_url']; ?>" data-pid="<?php echo $c;?>" class="play-img" src="<?php echo base_url();?>assest/images/new-theme/icon/play-ico.png" />
<div id="iframe_v_<?php echo $c;?>" style="display:none;"></div></div>
</div>
						<div class="col-md-7" style="padding-left:0px;margin-left:-7px;display:none;">
						<h3><b><?php echo $video['v_title']; ?></b></h3>
						<div class="discrip"><?php echo substr($video['v_content'],0,150); ?></div>
						<p>1025 Views - <?php echo $video['created_at']; ?></p></div>
					</div>
				</div>
				<?php $c++; } ?>
			<?php } else{ ?>
					No Videos.
			<?php } ?>
			</div>
		</div>
<div class="about-sec col-lg-5 col-sm-5 wow fadeInUp" data-wow-delay="0.5s" style="width:45.666667%;">
<div class="sidebar-header-title"><span class="e-text"><?php echo $this->lang->line('enam');?> OVERVIEW</span></div>
<?php print_r($home_body[0]['content']); ?>
</div>
		
		<div style="display:none;" class="col-lg-3 col-sm-3 wow fadeInUp events-box" data-wow-delay="0.5s" >
			<div style="width:110%;" class="sidebar-header-title"><span class="e-text"><?php echo $this->lang->line('enam');?> <?php echo $this->lang->line('news&events');?></span></div>
			<?php if((count($events) > 0) && (isset($events))){ ?>
				<?php $c=1; foreach($events as $event){ 
					if($c < 3){
					$event_title = strlen($event['title']) > 50 ? substr($event['title'],0,50)."..." : $event['title'];
					?>
					<div class="events-de">
						<div class="register-user-box">
							<b><?php echo $event_title; ?></b>
							<b><?php //echo $event['event_content'];?> </b>
						</div>
						<img style="width:100%;" alt="<?php echo $event['title']; ?>" src="<?php echo base_url(); ?>/Event_gallary/<?php echo $event['event_image']; ?>" />
					</div>
				<?php $c++; } } ?>
			<?php } else { ?>
				<div class="well text-danger">No Events Found.</div>
			<?php }?>
		</div>
		
		<div class="col-lg-4 col-sm-4 home-n wow fadeInRight" data-wow-delay="0.5s">
                       
			<div class="focus-section">
<div class="sidebar-header-title"><span><?php echo $this->lang->line('enam');?> <?php echo $this->lang->line('important_link');?></span></div>

                        <?php /* if($this->session->userdata('client_language') == 1) {?>
                           <a data-toggle="modal" data-target="#state_click"><img  src="<?php echo base_url();?>/assest/images/new-theme/map.jpg" usemap="#image-map"></a>
			<?php } else {?>
 		           <a data-toggle="modal" data-target="#state_click"><img style="width:100%;" src="<?php echo base_url();?>/assest/images/new-theme/hindi-map.jpg"></a>
<?php } */ ?>
<img  src="<?php echo base_url();?>/assest/images/new-theme/map.jpg" usemap="#image-map">
<!-- Image Map Generated by http://www.image-map.net/ -->
<!--<img src="map.jpg" >-->
<div class="map-mandi-no">
<div data-sate_id="43" title="HIMACHAL PRADESH" class="map-mandi-no-box state_district" id="sate_id_43" style="top:97px;left:132px;">18</div>
<div data-sate_id="602" title="PANJAB" class="map-mandi-no-box state_district" id="sate_id_602" style="top:108px;left:112px;">19</div>
<div data-sate_id="385" title="UTTARAKHAND" class="map-mandi-no-box state_district" id="sate_id_385" style="top:116px;left:150px;">16</div>
<div data-sate_id="32" title="HARYANA" class="map-mandi-no-box state_district" id="sate_id_32" style="top:127px;left:119px;">54</div>
<div data-sate_id="26" title="RAJASTHAN" class="map-mandi-no-box state_district" id="sate_id_26" style="top:160px;left:92px;">25</div>
<div data-sate_id="46" title="UTTAR PRADESH" class="map-mandi-no-box state_district" id="sate_id_46" style="top:160px;left:165px;">100</div>
<div data-sate_id="22" title="GUJARAT" class="map-mandi-no-box state_district" id="sate_id_22" style="top:200px;left:68px;">79</div>
<div data-sate_id="20" title="MADHYA PRADESH" class="map-mandi-no-box state_district" id="sate_id_20" style="top:200px;left:145px;">58</div>
<div data-sate_id="47" title="JHARKHAND" class="map-mandi-no-box state_district" id="sate_id_47" style="top:195px;left:215px;">19</div>
<div data-sate_id="569" title="WESTBENGAL" class="map-mandi-no-box state_district" id="sate_id_569" style="top:200px;left:241px;">17</div>
<div data-sate_id="100" title="CHHATTISGARH" class="map-mandi-no-box state_district" id="sate_id_100" style="top:226px;left:176px;">10</div>
<div data-sate_id="384" title="ODISHA" class="map-mandi-no-box state_district" id="sate_id_384" style="top:230px;left:215px;">14</div>
<div data-sate_id="296" title="MAHARASHTRA" class="map-mandi-no-box state_district" id="sate_id_296" style="top:245px;left:115px;">60</div>
<div data-sate_id="28" title="TELANGANA" class="map-mandi-no-box state_district" id="sate_id_28" style="top:265px;left:150px;">47</div>
<div data-sate_id="276" title="ANDHRA PRADESH" class="map-mandi-no-box state_district" id="sate_id_276" style="top:300px;left:145px;">22</div>
<div data-sate_id="509" title="TAMIL NADU" class="map-mandi-no-box state_district" id="sate_id_509" style="top:348px;left:138px;">23</div>
</div>

<map name="image-map">
    <area data-sate_id="26" class="state_district" data-toggle="modal" data-target="#state_click" alt="RAJASTHAN" title="RAJASTHAN"  coords="68,106,62,113,54,120,63,126,67,140,75,147,82,149,92,152,96,157,102,169,103,176,110,169,113,163,113,156,120,147,124,155,133,154,132,143,133,135,140,131,146,125,143,119,134,111,128,109,124,104,121,98,118,92,111,89,104,85,94,95,90,100,81,108,74,107,123,57" shape="poly">
    <area data-sate_id="602" class="state_district" alt="PANJAB" title="PANJAB" coords="125,58,126,64,129,69,134,71,134,82,126,86,120,89,114,88,106,83,111,75,114,64,119,60" shape="poly">
    <area data-sate_id="43" class="state_district" alt="HIMACHAL PRADESH" title="HIMACHAL PRADESH" coords="136,47,127,51,124,60,129,71,135,72,135,78,140,81,146,76,155,73,157,63,150,55" shape="poly">
    <area data-sate_id="32" class="state_district" alt="HARYANA" title="HARYANA"  coords="138,111,129,111,123,105,117,98,109,87,126,88,134,85,143,83,137,93,137,100,140,105" shape="poly">
    <area data-sate_id="385" class="state_district" alt="UTTARAKHAND" title="UTTARAKHAND"  coords="169,101,158,98,151,94,146,90,141,83,143,77,151,75,158,71,164,75,171,79,175,88" shape="poly">
    <area data-sate_id="22" class="state_district" alt="GUJARAT" title="GUJARAT" coords="41,155,48,150,62,152,72,151,86,151,95,161,98,171,98,179,97,187,95,195,90,199,84,180,79,185,71,191,61,192,55,188,48,179,55,170,59,166,47,167,41,163" shape="poly">
    <area data-sate_id="296" class="state_district" alt="MAHARASHTRA" title="MAHARASHTRA"  coords="88,200,86,214,86,223,89,229,90,236,88,242,89,249,96,256,103,254,106,246,117,243,125,237,138,228,142,223,147,214,152,209,163,214,170,219,174,212,173,203,175,192,167,191,153,189,142,189,136,187,129,193,117,186,105,185" shape="poly">
    <area data-sate_id="28" class="state_district" alt="TELANGANA" title="TELANGANA" coords="137,253,147,258,156,251,159,246,167,244,177,242,185,239,180,232,174,224,168,220,162,215,149,211,138,220,138,226,138,233,137,242" shape="poly">
    <area data-sate_id="276" class="state_district" alt="ANDHRA PRADESH" title="ANDHRA PRADESH"  coords="141,255,135,259,135,266,137,273,135,280,147,285,160,288,170,284,173,277,173,261,181,254,191,249,198,240,209,234,216,227,223,217,213,214,206,218,205,224,196,224,187,230,186,236,173,242,164,246,159,253,148,254" shape="poly">
    <area data-sate_id="509" class="state_district" alt="TAMIL NADU" title="TAMIL NADU" coords="135,351,132,342,133,332,131,323,126,317,125,310,133,309,141,302,140,294,148,294,155,288,167,285,168,299,166,308,163,317,161,324,158,330,150,337,144,344,141,349" shape="poly">
    <area data-sate_id="384" class="state_district" alt="ODISHA" title="ODISHA"  coords="224,183,214,180,206,190,201,195,194,200,195,206,190,210,191,219,187,226,198,225,207,222,216,217,222,215,231,208,239,204,243,195,248,184,243,181,235,177,231,183" shape="poly">
    <area data-sate_id="100" class="state_district" alt="CHHATTISGARH" title="CHHATTISGARH"  coords="181,231,176,223,170,219,172,209,170,196,171,190,177,180,185,169,188,164,195,158,204,159,209,168,209,176,202,188,193,208,191,218,187,226" shape="poly">
    <area data-sate_id="569" class="state_district" alt="WESTBENGAL" title="WESTBENGAL" coords="255,181,245,179,242,173,233,169,240,163,248,156,254,152,251,141,258,136,261,143,257,147,261,152,265,159,267,168,267,175,263,180" shape="poly">
    <area data-sate_id="47" class="state_district" alt="JHARKHAND" title="JHARKHAND" coords="216,175,210,167,204,158,210,152,221,152,228,153,235,150,242,148,251,141,255,147,248,153,244,158,237,165,237,173,229,180" shape="poly">
    <area data-sate_id="20" class="state_district" alt="MADHYA PRADESH" title="MADHYA PRADESH"  coords="104,182,107,175,113,168,113,158,112,151,120,148,121,155,129,155,134,149,132,141,132,134,140,129,148,127,154,124,159,131,156,136,150,143,153,155,156,145,165,144,183,146,194,152,189,163,185,169,179,181,168,188,153,186,143,188,132,187,120,188" shape="poly">
    <area data-sate_id="46" class="state_district" alt="UTTAR PRADESH" title="UTTAR PRADESH"  coords="142,86,139,95,140,108,141,116,145,125,153,125,157,132,156,143,163,142,172,143,181,145,190,150,195,158,202,150,203,143,212,139,212,130,211,123,199,117,184,109,174,103,161,99,151,93" shape="poly">
</map>




<a href="<?php echo base_url();?>emandi" class="map-detail-btn">Note: Click on the states to view details</a>				
<div class="booklet-section" style="display:none;">
					<ul>
						<li><a title="eNAM Booklet" href=""><img alt="Logistic Details" src="<?php echo base_url();?>assest/images/new-theme/icon/booklet.png" /> <span><?php echo $this->lang->line('download');?></span><br><?php echo $this->lang->line('eNAM_Booklet');?></a></li>
						<li><a title="Guidelines  Manual" href="guide.html"><img alt="Logistic Details" src="<?php echo base_url();?>assest/images/new-theme/icon/guideline.png" /><span><?php echo $this->lang->line('registration');?></span><br><?php echo $this->lang->line('guidelines_manual');?></a></li>
					</ul>
				</div>
</div>
		</div>
	</div></div>
</section>

<div id="state_click" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content mandis-list-pop">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <!--<h4 style="width:50%;" class="modal-title pull-left"><b>State: <span id="state_name"></span></b></h4><h4 class="pull-right" style="width:47%;margin:0px;" >Total Mandis: <span id="total_mandi"></span></h4>-->
<table class="table table-bordered" style="background-color:#e8e8e8;">
<tbody>
<tr><td style="width:50%;border-right:1px solid #c7c2c2;background-color:#252525;"><h4><b>STATE:</b></h4></td><td style="background-color:#252525;"><h4><b>TOTAL MANDIS:</b></h4></td></tr>
<tr><td style="width:50%;border-right:1px solid #c7c2c2;"><h4 style="color:#000"><b><span id="state_name"></span></b></h4></td><td><h4 style="color:#000"><b><span id="total_mandi"></span></b></h4></td></tr>
</tbody>
</table>
      </div>
      <div class="modal-body mandi-table-h">
        <table class="table table-bordered table-striped" id="mandis_list">
		</table>
			</br>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

<script>
var baseUrl = $('#base_url').val();

$(document).on('click','.state_district',function(){
	var state_id = $(this).data('sate_id');
	$.ajax({
	    type: 'POST',
	    url: baseUrl + 'ajax_ctrl/get_district_map',
	    dataType: "json",
	    data: {
	    	'state_id' : state_id
	    },
	    beforeSend: function(){
	    	$('#loader').modal({'show':true});	
	    },
	    complete: function(){},
	    success:function (response) {
               $('#loader').modal('toggle');
	    	console.log(response);
	    	if(response.status == 200){
		    	var x = '<tr><th style="width:50%;">District</th><th>Commodity Details</th></tr>';
				var counter = 0;
		    	$.each(response.data,function(key,value){
					if(key < 11){
						x = x +  '<tr><td>'+ value.district_name +'</td><td>'+
						'<a href="'+baseUrl+'emandi/'+state_id+'/'+ value.district_id +'"  data-district_id="'+ value.district_name +'" class="btn btn-sm btn-success district_btn" href="">View</a></td></tr>';
					}
		    	});
		    	var y = '<a href="'+baseUrl+'emandi/'+state_id+'" title="View all" data-state_id="'+ state_id +'" class="btn btn-success" href="">View All</a>'+
		                '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>'; 
		    	$('.modal-footer').html(y);
		    	$('#state_click').modal('show');
		    	$('#mandis_list').html(x);
				$('#state_name').html(response.data[0].state_name);
				$('#total_mandi').html(response.count[0].total);
	    	}
	    	else{
	    		alert('data not available for this state.');
	    	}
	    }
	});
});

$.ajax({
    type: 'POST',
    url: baseUrl + 'ajax_ctrl/get_mandi_count',
    dataType: "json",
    data: {
    	
    },
    beforeSend: function(){
    	$('#loader').modal({'show':true});	
    },
    complete: function(){},
    success:function (response) {
    	console.log(response);
    	if(response.status == 200){
	    	var x = '';
			var counter = 0;
			$.each(response.data,function(key,value){
				$('#sate_id_'+key).html(value);	    		
			});
    	}
    }
});

</script>